MyLibrary/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MyLibrary.DataRepository;
using MyLibrary.Models;

namespace MyLibrary.Controllers
{
    /// <summary>
    /// This class is used to create and view books
    /// </summary>
    public class BookController : Controller
    {
        private readonly IRepository _repository;

        public BookController(IRepository repository)
        {
            this._repository = repository;
        }

        /// <summary>
        /// This Create action creates an empty view to add a book
        /// </summary>
        /// <returns>ActionResult</returns>
        [HttpGet]
        public virtual ActionResult Create()
        {
            return View(new BookViewModel());
        }

        /// <summary>
        /// When create button click this Create action gets the BookViewModel with values
        /// If all the conditions are met the book get added and redirect to Create action
        /// </summary>
        /// <param name="model"></param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        public virtual ActionResult Create(BookViewModel model)
        {
            if (!ModelState.IsValid)
               return View(model);

            model.Id = Guid.NewGuid();
            _repository.AddBook(model);

           return RedirectToAction("Create");
        }

        /// <summary>
        /// This ViewBooks action return a view with list of added books
        /// </summary>
        /// <returns>ActionResult</returns>
        [HttpGet]
        public virtual ActionResult ViewBooks()
        {
            return View(_repository.GetBooks());
        }

        [HttpGet]
        public virtual ActionResult Search()
        {
            return View(new BookSearchViewModel());
        }

        [HttpPost]
        public virtual ActionResult Search(BookSearchViewModel model)
        {
            model.Books = _repository.GetBooks(model.Title, model.Author);

            if (!model.Books.Any())
            {
                model.SearchResultInfo = "No matching books were found, please adjust your search and try again.";
            }

            return View(model);
        }
    }
}

MyLibrary/Controllers/BorrowerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MyLibrary.DataRepository;
using MyLibrary.Models;

namespace MyLibrary.Controllers
{
    /// <summary>
    /// This class is used to create and view borrowers
    /// </summary>
    public class BorrowerController : Controller
    {
        private readonly IRepository _repository;

        public BorrowerController(IRepository repository)
        {
            this._repository = repository;
        }

        /// <summary>
        /// This Create action creates an empty view to add a borrower
        /// </summary>
        /// <returns>ActionResult</returns>
        [HttpGet]
        public virtual ActionResult Create()
        {
            return View(new Borrower());
        }

        /// <summary>
        /// When create button click this Create action gets the BorrowerViewModel with values
        /// If all the conditions are met the Borrower get added and redirect to Create action
        /// </summary>
        /// <param name="model"></param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        public virtual ActionResult Create(Borrower model)
        {
           if (!ModelState.IsValid)
               return View(model);

           model.Id = Guid.NewGuid();
           _repository.AddBorrower(model);

           return RedirectToAction("Create");
        }

        /// <summary>
        /// This ViewBooks action return a view with list of added books
        /// </summary>
        /// <returns>ActionResult</returns>
        [HttpGet]
        public virtual ActionResult ViewBorrowers()
        {
            return View(_repository.GetBorrowers());
        }

        [HttpGet]
        public virtual ActionResult OverdueBooks()
        {
            var overdueBooks = _repository.GetOverdueBooks();
            return View(overdueBooks);
        }

        [HttpGet]
        public virtual ActionResult BorrowBook(Guid bookId)
        {
            var book = _repository.GetBook(bookId);

            return View(new BorrowBookViewModel
            {
                Book = book
            });
        }

        [HttpPost]
        public virtual ActionResult BorrowBook(BorrowBookViewModel model)
        {
            // choosing to use the query string here to re-load the book data, 
            // another option was to have the book id as hidden field in the form
            // even better solution is to evolve the application to always be in the context of a real libray member, i.e. when they scan in
            // the last option would make borrowing quicker, it would be about finding a book (again scanning a barcode).
            model.Book = _repository.GetBook(Guid.Parse(Request.QueryString["bookId"]));

            model.Borrowers = _repository.GetBorrowers(model.Borrower.FirstName, model.Borrower.LastName).ToList();

            if (!model.Borrowers.Any())
            {
                model.SearchResultInfo = "No matching borrowers were found, please adjust your search and try again.";
            }

            return View(model);
        }

        [HttpPost]
        public virtual ActionResult CheckoutBook(Guid bookId, Guid borrowerId)
        {
            var result = _repository.BorrowBook(bookId, borrowerId);

            return View(result);
        }
    }
}

MyLibrary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My Library</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-brand">
                    My Library
                </div>
                </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Add Books", "Create", "Book", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Search Books", "Search", "Book", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Add Borrowers", "Create", "Borrower", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Overdue Books", "OverdueBooks", "Borrower", new { area = "" }, null)</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()   
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", false)
</body>
</html>